apiVersion: apps/v1
kind: Deployment
metadata:
  name: abler-search-api
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: abler-search-api
  template:
    metadata:
      labels:
        app: abler-search-api
    spec:
      containers:
        - name: abler-search-api
          image: produtosabler/abler-search-api:${{ github.sha }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          # resources:
          #   requests:
          #     cpu: 2
          #     memory: 2Gi
          #   limits:
          #     cpu: 3
          #     memory: 3Gi
      imagePullSecrets:
        - name: acr-secret # container-registry
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: run
                operator: In
                values:
                - front

